export const FORMULARIO_SECCION = 'FORMULARIO_SECCION';
export const OBTENER_SECCIONES = 'OBTENER_SECCIONES';
export const AGREGAR_SECCIONES = 'AGREGAR_SECCIONES';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const SECCION_ACTUAL = 'SECCION_ACTUAL';
export const ELIMINAR_SECCION = 'ELIMINAR_SECCION';