// secciones
export const FORMULARIO_SECCION = 'FORMULARIO_SECCION';
export const OBTENER_SECCIONES = 'OBTENER_SECCIONES';
export const AGREGAR_SECCIONES = 'AGREGAR_SECCIONES';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const SECCION_ACTUAL = 'SECCION_ACTUAL';
export const ELIMINAR_SECCION = 'ELIMINAR_SECCION';
// imágenes
export const IMAGENES_SECCIONES = 'IMAGENES_SECCIONES';
export const AGREGAR_IMAGEN = 'AGREGAR_IMAGEN';
export const VALIDAR_IMAGEN = 'VALIDAR_IMAGEN';
export const ELIMINAR_IMAGEN = 'ELIMINAR_IMAGEN';
export const ESTADO_IMAGEN = 'ESTADO_IMAGEN';
export const IMAGEN_ACTUAL = 'IMAGEN_ACTUAL';
export const ACTUALIZAR_IMAGEN = 'ACTUALIZAR_IMAGEN';
export const LIMPIAR_IMAGEN = 'LIMPIAR_IMAGEN';
// alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';
// auth
export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO';
export const REGISTRO_ERROR = 'REGISTRO_ERROR';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';