// secciones
export const FORMULARIO_SECCION = 'FORMULARIO_SECCION';
export const OBTENER_SECCIONES = 'OBTENER_SECCIONES';
export const AGREGAR_SECCIONES = 'AGREGAR_SECCIONES';
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const SECCION_ACTUAL = 'SECCION_ACTUAL';
export const ELIMINAR_SECCION = 'ELIMINAR_SECCION';
// imágenes
export const IMAGENES_SECCIONES = 'IMAGENES_SECCIONES';
export const AGREGAR_IMAGEN = 'AGREGAR_IMAGEN';
export const VALIDAR_IMAGEN = 'VALIDAR_IMAGEN';
export const ELIMINAR_IMAGEN = 'ELIMINAR_IMAGEN';
export const ESTADO_IMAGEN = 'ESTADO_IMAGEN';
export const IMAGEN_ACTUAL = 'IMAGEN_ACTUAL';
export const ACTUALIZAR_IMAGEN = 'ACTUALIZAR_IMAGEN';
export const LIMPIAR_IMAGEN = 'LIMPIAR_IMAGEN';
// alertas
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';